### ISSUE TITLE
Add customization options

### ISSUE THREAD

**Issue by martinthiemann** [jacopocolo/stamp-artboards-name#4]
It would be great to have options to customize position on artboard, font size, background color of the stamp.

**Comment by martinthiemann** [comment]
![stamp-artboard-names-plugin-ui](https://user-images.githubusercontent.com/1038364/52045455-dc90ed00-2544-11e9-8538-c0d092be3d13.png)

**Comment by jacopocolo** [comment]
Ok, I solved this with the release 1.0. It doesn't have a UI (because it's a lot of work to build a UI for this) but from the plugin you can open a file that contains these preferences, change and save them.
